### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by cand126** [omni-us/pagexml#1]
Here I have some questions regarding this project:

1. Why there are two copies of `PageXML.h` and `PageXML.cc`? (one in /lib and another one in /py-pagexml/pagexml)
2. Is it possible to provide a Python3.7 version?
3. Is it possible to use python functions without loading opencv library? Some functions, e.g., `PageXML::setProperty`, do not require opencv library.

**Comment by mauvilsa** [comment]
@cand126 answering your questions:

1. There is only one copy of `PageXML.h` and `PageXML.cc` in the `lib` directory. In `py-pagexml/pagexml` there are only symlinks to the files in the `lib` directory. If you are using windows then I am not sure what happens exactly since there symlinks are not supported and I don't use windows so have never seen it.

2. No, we will not provide a precompiled wheel file for python3.7, so you need to build it yourself, but it should work without problem in linux and mac. The python package is based on the c++ library, so it needs to be compiled. Even the wheel files that are available now do not work on any python3.5 or python3.6 since it depends on libraries from the OS. Thus, these only work in Ubuntu 16.04 (the one for python 3.5) and in Ubuntu 18.04 (the one for python 3.6).

3. The opencv library is required. Even though the library is prepared to be able to exclude some libraries, e.g. gdal, it is not the case for opencv.
