### ISSUE TITLE
Couldn't find wheel file for python3.6 with ubuntu 20. Please help me. 

### ISSUE THREAD

**Issue by VishnuGopireddy** [omni-us/pagexml#3]
I am on ubuntu 20.04 with python 3.6, for ubuntu 20.04 the available libopencv-imgcodecs are with 4.2. But pagexml configuration for python 3.6 accepts libopencv-imgcodecs version of 3.2, no installation for python 3.6 and libopencv-imgcodecs 3.2. Can you please help me out.

**Comment by mauvilsa** [comment]
Since the wheels depend on os libraries it is simply impractical to prebuild them for every possible python version and os combination. This is why there are only three prebuilt wheels each intended for the default python version of each ubuntu LTS release: ubuntu 16.04 -> python 3.5; ubuntu 18.04 -> python 3.6; ubuntu 20.04 -> python 3.8.

If really don't want to use python 3.8 since you are using ubuntu 20.04, then you need to compile the wheel from source.
